### ISSUE TITLE
Sass::SyntaxError: Undefined mixin 'rounded'

### ISSUE THREAD

**Issue by atistler** [rstgroup/active_skin#30]
Getting the following error when precompiling.  active_skin works fine in development.

Sass::SyntaxError: Undefined mixin 'rounded'.
  (in /srv/app/shared/bundle/ruby/2.0.0/gems/active_skin-0.0.12/app/assets/stylesheets/active_skin.sass)
/srv/app/shared/bundle/ruby/2.0.0/gems/active_skin-0.0.12/app/assets/stylesheets/active_skin.sass:42:in `rounded'
/srv/app/shared/bundle/ruby/2.0.0/gems/active_skin-0.0.12/app/assets/stylesheets/active_skin.sass:42
/srv/app/shared/bundle/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:349:in `block in visit_mixin'
/srv/app/shared/bundle/ruby/2.0.0/gems/sass-3.4.21/lib/sass/stack.rb:98:in `block in with_mixin'
/srv/app/shared/bundle/ruby/2.0.0/gems/sass-3.4.21/lib/sass/stack.rb:115:in `with_frame'
/srv/app/shared/bundle/ruby/2.0.0/gems/sass-3.4.21/lib/sass/stack.rb:98:in `with_mixin'
/srv/app/shared/bundle/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:347:in `visit_mixin'
/srv/app/shared/bundle/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/base.rb:36:in `visit'
/srv/app/shared/bundle/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
/srv/app/shared/bundle/ruby/2.0.0/gems/sass-3.4.21/lib/sass/stack.rb:79:in `block in with_base'
/srv/app/shared/bundle/ruby/2.0.0/gems/sass-3.4.21/lib/sass/stack.rb:115:in `with_frame'
/srv/app/shared/bundle/ruby/2.0.0/gems/sass-3.4.21/lib/sass/stack.rb:79:in `with_base'
/srv/app/shared/bundle/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:158:in `visit'
/srv/app/shared/bundle/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:431:in `block (2 levels) in visit_rule'
/srv/app/shared/bundle/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:431:in `map'
/srv/app/shared/bundle/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:431:in `block in visit_rule'
/srv/app/shared/bundle/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
/srv/app/shared/bundle/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:429:in `visit_rule'
/srv/app/shared/bundle/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/base.rb:36:in `visit'
/srv/app/shared/bundle/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
/srv/app/shared/bundle/ruby/2.0.0/gems/sass-3.4.21/lib/sass/stack.rb:79:in `block in with_base'
/srv/app/shared/bundle/ruby/2.0.0/gems/sass-3.4.21/lib/sass/stack.rb:115:in `with_frame'
/srv/app/shared/bundle/ruby/2.0.0/gems/sass-3.4.21/lib/sass/stack.rb:79:in `with_base'
/srv/app/shared/bundle/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:158:in `visit'
/srv/app/shared/bundle/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:431:in `block (2 levels) in visit_rule'
/srv/app/shared/bundle/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:431:in `map'
/srv/app/shared/bundle/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:431:in `block in visit_rule'
/srv/app/shared/bundle/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
/srv/app/shared/bundle/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:429:in `visit_rule'
/srv/app/shared/bundle/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/base.rb:36:in `visit'
/srv/app/shared/bundle/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
/srv/app/shared/bundle/ruby/2.0.0/gems/sass-3.4.21/lib/sass/stack.rb:79:in `block in with_base'
/srv/app/shared/bundle/ruby/2.0.0/gems/sass-3.4.21/lib/sass/stack.rb:115:in `with_frame'
/srv/app/shared/bundle/ruby/2.0.0/gems/sass-3.4.21/lib/sass/stack.rb:79:in `with_base'
/srv/app/shared/bundle/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:158:in `visit'
/srv/app/shared/bundle/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
/srv/app/shared/bundle/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/base.rb:52:in `map'
/srv/app/shared/bundle/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/base.rb:52:in `visit_children'
/srv/app/shared/bundle/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:167:in `block in visit_children'
/srv/app/shared/bundle/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
/srv/app/shared/bundle/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:166:in `visit_children'
/srv/app/shared/bundle/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/base.rb:36:in `block in visit'
/srv/app/shared/bundle/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:186:in `visit_root'
/srv/app/shared/bundle/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/base.rb:36:in `visit'
/srv/app/shared/bundle/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:157:in `visit'
/srv/app/shared/bundle/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/visitors/perform.rb:8:in `visit'
/srv/app/shared/bundle/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/root_node.rb:36:in `css_tree'
/srv/app/shared/bundle/ruby/2.0.0/gems/sass-3.4.21/lib/sass/tree/root_node.rb:20:in `render'
/srv/app/shared/bundle/ruby/2.0.0/gems/sass-3.4.21/lib/sass/engine.rb:278:in `render'
/srv/app/shared/bundle/ruby/2.0.0/gems/sass-rails-3.2.6/lib/sass/rails/template_handlers.rb:106:in `evaluate'
/srv/app/shared/bundle/ruby/2.0.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
/srv/app/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.3/lib/sprockets/context.rb:193:in `block in evaluate'
/srv/app/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.3/lib/sprockets/context.rb:190:in `each'
/srv/app/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.3/lib/sprockets/context.rb:190:in `evaluate'
/srv/app/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.3/lib/sprockets/processed_asset.rb:12:in `initialize'
/srv/app/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:249:in `new'
/srv/app/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:249:in `block in build_asset'
/srv/app/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:270:in `circular_call_protection'
/srv/app/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:248:in `build_asset'
/srv/app/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.3/lib/sprockets/index.rb:93:in `block in build_asset'
/srv/app/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.3/lib/sprockets/caching.rb:19:in `cache_asset'
/srv/app/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.3/lib/sprockets/index.rb:92:in `build_asset'
/srv/app/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:169:in `find_asset'
/srv/app/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.3/lib/sprockets/index.rb:60:in `find_asset'
/srv/app/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.3/lib/sprockets/bundled_asset.rb:16:in `initialize'
/srv/app/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:252:in `new'
/srv/app/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:252:in `build_asset'
/srv/app/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.3/lib/sprockets/index.rb:93:in `block in build_asset'
/srv/app/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.3/lib/sprockets/caching.rb:19:in `cache_asset'
/srv/app/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.3/lib/sprockets/index.rb:92:in `build_asset'
/srv/app/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:169:in `find_asset'
/srv/app/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.3/lib/sprockets/index.rb:60:in `find_asset'
/srv/app/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/sprockets/static_compiler.rb:19:in `block in compile'
/srv/app/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:219:in `block in each_logical_path'
/srv/app/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:206:in `block (2 levels) in each_file'
/srv/app/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:196:in `each'
/srv/app/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:196:in `each_entry'
/srv/app/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:204:in `block in each_file'
/srv/app/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:203:in `each'
/srv/app/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:203:in `each_file'
/srv/app/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:217:in `each_logical_path'
/srv/app/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/sprockets/static_compiler.rb:18:in `compile'
/srv/app/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/sprockets/assets.rake:56:in `internal_precompile'
/srv/app/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/sprockets/assets.rake:70:in `block (3 levels) in <top (required)>'
/srv/app/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.19/lib/sprockets/assets.rake:60:in `block (3 levels) in <top (required)>'
Tasks: TOP => assets:precompile:primary

**Comment by atistler** [comment]
Here is my active_admin.css.scss

```
// SASS variable overrides must be declared before loading up Active Admin's styles.
//
// To view the variables that Active Admin provides, take a look at
// `app/assets/stylesheets/active_admin/mixins/_variables.css.scss` in the
// Active Admin source.
//
// For example, to change the sidebar width:
// $sidebar-width: 242px;
// Active Admin's got SASS!
@import "active_admin/mixins";
@import "active_admin/base";
// Overriding any non-variable SASS must be done after the fact.
// For example, to change the default status-tag color:
//
//   body.active_admin {
//      .status_tag { background: #6090DB; }
//   }
//
// Notice that Active Admin CSS rules are nested within a
// 'body.active_admin' selector to prevent conflicts with
// other pages in the app. It is best to wrap your changes in a 
// namespace so they are properly recognized. You have options
// if you e.g. want different styles for different namespaces:
//
// .active_admin       applies to any Active Admin namespace
// .admin_namespace    applies to the admin namespace (eg: /admin)
// .other_namespace    applies to a custom namespace named other (eg: /other)


$skinActiveColor: #356AA0;
$skinHeaderBck: #002744;
$panelHeaderBck: #356AA0;
$skinLogo: url("top_logo.gif") no-repeat 0 0;

@import "active_skin";
@import "active_admin/select2/base";

/*
#header {
  h1.site_title {
    background-size: 150px 35px;
    background-position: 2px 5px;
  }
}
*/

#title_bar .action_items span.action_item > a {
  padding: 10px;
}

#title_bar h2 {
  font-size: 1.8em;
  text-transform: uppercase;
}

form .input textarea.code {
  font-family: monospace;
}

.show .panel tr.code td {
  font-family: monospace;
  white-space: pre-wrap;
}
```

**Comment by juangesino** [comment]
I'm getting the same error in production precompiling (works fine in development).

**Comment by shivasms65** [comment]
I'm getting the same error in production precompiling, its resolved are not, am using active_skin (0.0.12)

**Comment by loveyhtu21** [comment]
I'm getting the same error in production precompiling (works fine in development).

**Comment by shivasms65** [comment]
Instead of Using gem use the file they provided directly it will work

**Comment by VABritto** [comment]
> Instead of Using gem use the file they provided directly it will work

Didn't work for me. Am having the same exact problem.
